In [3]:
import numpy as np
import pandas as pd

In [16]:
pd = pd.read_csv(r'../data/infection_summary_demo1.csv')

In [17]:
for i in range(len(pd)):
    if pd.loc[i, 'Assis'] == 'D':
        pd = pd.drop(i)
pd

,time_stamp,susceptible,exposed,asymptomatic,symptomatic,severe,recovered,Assis
0,3,740,0,10,0,0,0,K
2,7,740,0,10,0,0,0,K
4,11,740,0,10,0,0,0,K
6,15,740,0,10,0,0,0,K
8,19,740,0,10,0,0,0,K
10,23,740,0,10,0,0,0,K
12,27,740,0,10,0,0,0,K
14,31,740,0,10,0,0,0,K
15,33,740,0,10,0,0,0,K
17,37,740,0,10,0,0,0,K
19,41,740,0,10,0,0,0,K
21,45,740,0,10,0,0,0,K
23,49,740,0,10,0,0,0,K
25,53,740,0,10,0,0,0,K
27,57,740,0,10,0,0,0,K
29,61,740,0,10,0,0,0,K
30,63,740,0,10,0,0,0,K
32,67,740,0,10,0,0,0,K
34,71,740,0,10,0,0,0,K
36,75,740,0,10,0,0,0,K
38,79,740,0,10,0,0,0,K
40,83,740,0,10,0,0,0,K
42,87,740,0,10,0,0,0,K
44,91,740,0,10,0,0,0,K
45,93,740,0,10,0,0,0,K
47,97,740,0,10,0,0,0,K
49,101,740,0,10,0,0,0,K
51,105,740,0,10,0,0,0,K
53,109,740,0,10,0,0,0,K
55,113,740,0,10,0,0,0,K
...,...,...,...,...,...,...,...,...
93049,186101,521,3,6,27,14,179,K
93051,186105,521,3,6,27,14,179,K
93053,186109,521,3,6,27,14,179,K
93055,186113,521,3,6,27,14,179,K
93057,186117,521,3,6,27,14,179,K
93059,186121,521,3,6,27,14,179,K
93060,186123,521,3,6,27,14,179,K
93062,186127,521,3,6,27,14,179,K
93064,186131,521,3,6,27,14,179,K
93066,186135,521,3,6,27,14,179,K
93068,186139,521,3,6,27,14,179,K
93070,186143,521,3,6,27,14,179,K
93072,186147,521,3,6,27,14,179,K
93074,186151,521,3,6,27,14,179,K
93075,186153,521,3,6,27,14,179,K
93077,186157,521,3,6,27,14,179,K
93079,186161,521,3,6,27,14,179,K
93081,186165,521,3,6,27,14,179,K
93083,186169,521,3,6,27,14,179,K
93085,186173,521,3,6,27,14,179,K
93087,186177,521,3,6,27,14,179,K
93089,186181,521,3,6,27,14,179,K
93090,186183,521,3,6,27,14,179,K
93092,186187,521,3,6,27,14,179,K
93094,186191,521,3,6,27,14,179,K
93096,186195,521,3,6,27,14,179,K
93098,186199,521,3,6,27,14,179,K
93100,186203,521,3,6,27,14,179,K
93102,186207,521,3,6,27,14,179,K
93104,186211,521,3,6,27,14,179,K

In [2]:
pd.to_csv('../data/infection_summary_demo1.csv')

AttributeError: module 'pandas' has no attribute 'to_csv'

In [4]:
business_map = pd.read_csv(r'../../../config/map/business.csv')

In [5]:
business_map

,building_type,min_workhour,max_workhour,min_start_hour,max_start_hour,day,min_activity_per_week,max_activity_per_week,open_24_hours_chance
0,restaurant,10,12,10,11,everyday,5,7,0.1
1,barbershop,8,12,9,11,everyday,5,7,0.0
2,retail,10,12,8,10,everyday,6,7,0.1
3,hospital,24,24,0,0,everyday,7,7,1.0
4,train_station,24,24,0,0,everyday,7,7,1.0

In [20]:
business_map['min_workhour'][0]

10

In [21]:
import os
os.getcwd()

'C:\\Users\\Jason\\Desktop\\Epidemicon Research\\experiment\\Koudou\\src\\dashapp\\jupyter'

In [6]:
import json
import pandas as pd
import os

evacuation_map = pd.read_json(os.getcwd()+'../../../config/map/evacuation_center.json', encoding="utf-8", orient='records')

ValueError: Expected object or value

In [17]:
from pandas.io.json import json_normalize

data=open('C:\\Users\\Jason\\Desktop\\Epidemicon Research\\experiment\\Koudou\\config\\map\\evacuation_center.json',encoding="utf-8").read()
data_list=json.loads(data)
df=json_normalize(data_list)

D:\conda\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  """

In [18]:
df

                                  evacuation_centers
0  [{'selection': 'by_id', 'rules': {'place_id': ...

In [21]:
df = pd.read_json('C:\\Users\\Jason\\Desktop\\Epidemicon Research\\experiment\\Koudou\\config\\map\\evacuation_center.json',
                encoding='utf-8',
                orient="records")
df

                                  evacuation_centers
0  {'selection': 'by_id', 'rules': {'place_id': '...
1  {'selection': 'by_id', 'rules': {'place_id': '...
2  {'selection': 'by_id', 'rules': {'place_id': '...
3  {'selection': 'by_id', 'rules': {'place_id': '...
4  {'selection': 'by_id', 'rules': {'place_id': '...
5  {'selection': 'by_id', 'rules': {'place_id': '...
6  {'selection': 'by_id', 'rules': {'place_id': '...
7  {'selection': 'by_id', 'rules': {'place_id': '...

In [26]:
df.iloc[0][0]

{'selection': 'by_id',
 'rules': {'place_id': '487758238'},
 'attributes': {'name': 'Kasuga Gakuen Obligatory Education School',
  'capacity': 1500,
  'contains_food': True,
  'contains_medicine': False}}

In [28]:
len(df.iloc[0][0]['attributes'])

4

In [35]:
df.iloc[1][0]['attributes'].keys()

dict_keys(['name', 'capacity', 'contains_food', 'contains_medicine'])

In [37]:
len(df)
evacuation_map = df

In [38]:
    value_list = []
    for i in range(len(evacuation_map)):
        single_list = []
        single_list.append(i+1)
        single_list.append(evacuation_map.iloc[i][0]["selection"])
        single_list.append(evacuation_map.iloc[i][0]["rules"]["place_id"])
        single_list.append(evacuation_map.iloc[i][0]["attributes"]["name"])
        single_list.append(evacuation_map.iloc[i][0]["attributes"]["capacity"])
        single_list.append(evacuation_map.iloc[i][0]["attributes"]["contains_food"])
        single_list.append(evacuation_map.iloc[i][0]["attributes"]["contains_medicine"])
        value_list.append(single_list)

In [39]:
value_list

[[1,
  'by_id',
  '487758238',
  'Kasuga Gakuen Obligatory Education School',
  1500,
  True,
  False],
 [2, 'by_id', '144198893', 'Azuma Elementary School', 1500, True, False],
 [3, 'by_id', '260552751', 'Kasuga Exchange Center', 1500, True, False],
 [4, 'by_id', '143970885', 'Tsukuba Capio', 1500, True, False],
 [5, 'by_id', '143801539', 'Tsukuba Innovation Plaza', 1500, True, False],
 [6, 'by_id', '216503324', 'Joyo Bank Azuma', 1500, True, False],
 [7, 'by_id', '281239292', 'Tsukuba Bank Headquarters', 1500, True, False],
 [8, 'by_id', '426073131', 'Azuma Exchange Center', 1500, True, False]]

In [1]:
f.open('log.txt')

NameError: name 'f' is not defined

In [3]:
f = open('C:\\Users\\Jason\Desktop\\Epidemicon Research\\experiment\\Koudou\\src\\dashapp\\data\\log_result\\log.txt')

In [4]:
f

In [5]:
lines = f.readlines()

In [9]:
len(lines)

339

In [10]:
lines[0]

'[debug] : List of Parameters\n'